### PR TITLE
Update db to unicode 13.0

### PR DESCRIPTION
**Pull request by tomgrin10**
I would love it if you would update the library in pypi after this PR is merged 😄

### CODE REVIEW

**Comment by tomgrin10** [comment]
What's the status with this?

**Comment by alexandrevicenzi** [comment]
@tomgrin10 merged.

**Comment by alexandrevicenzi** [comment]
New version on PyPI is 0.6.0.

**Comment by tomgrin10** [comment]
Thanks! 😄

**Pull request merged**
