### PR TITLE
Add iter function to iterate emojis in string

### PR DESCRIPTION
**Pull request by tomgrin10**
I needed to iterate emojis by order, so I added this function.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
The set is already ordered in get function.

Am I missing something?

**Comment by tomgrin10** [comment]
> The set is already ordered in get function.
> 
> Am I missing something?

Python `set`s are not ordered, I specifically noticed the `get` function wasn't ordered when I used it on the string `🇺🇸 🇬🇧`

**Comment by alexandrevicenzi** [comment]
The generator won't be sorted/ordered as well and neither unique. The generator will return all emojis found in the given order that they are found.

Perhaps is this what you want, if so, the comment/doc in the function does not really capture this behavior and can be misleading.

**Comment by tomgrin10** [comment]
> The generator won't be sorted/ordered as well and neither unique. The generator will return all emojis found in the given order that they are found.

Well, it does the job for me

> Perhaps is this what you want, if so, the comment/doc in the function does not really capture this behavior and can be misleading.

Would it be ok if I just remove the words `by order`?

**Comment by alexandrevicenzi** [comment]
Perhaps you could use: `Iterates over all emojis found in the message`

**Comment by tomgrin10** [comment]
> Perhaps you could use: `Iterates over all emojis found in the message`

Done😀

**Comment by alexandrevicenzi** [comment]
Thanks

**Pull request merged**
